lesson 4 - done
eugene-okulik/AoifeSidhe pull request #5
Opened 2023-12-14 01:23 UTC by AoifeSidhe

task - homework
notask - мой фаил для наглядного примера мне лично.

2023-12-14 02:04 UTC, AoifeSidhe commented
![image](https://github.com/eugene-okulik/AoifeSidhe/assets/127910230/694e59c5-0906-415a-8ee2-2e5d81b30a0d)

2023-12-14 07:51 UTC, eugene-okulik requested changes
Мне, видимо, нужно привыкнуть к тому, что ты будешь выполнять еще и задания, которые сама придумала )))  
В целом, по заданию всё выполнено, но проверку на внимательность не прошла ))

2023-12-14 07:51 UTC, eugene-okulik commented on homework/aoife_sidhe/lesson_4/task.py
> +my_dict['prices_dict']['i am a tuple'] = 100  # add a new item
В задании было

> добавьте элемент с ключом ('i am a tuple',) и любым значением

ты выполнила так, как если бы там было 

> добавьте элемент с ключом 'i am a tuple' и любым значением

2023-12-14 12:28 UTC, AoifeSidhe commented on homework/aoife_sidhe/lesson_4/task.py
> +my_dict['prices_dict']['i am a tuple'] = 100  # add a new item
Я думала, что  скобки это часть форматирования задания =)
Хотя запятую да, в упор не видела
Поправила. 
Задание на то, что надо правильно скобки включать?

И так пройдёт:
```
print("Adding new key-value pair for prices_dict - i am a tuple")
my_dict['prices_dict']['(\'i am a tuple\',)'] = 100
```

А так нет:
`my_dict['prices_dict']['('i am a tuple',)'] = 100  # add a new item`

![image](https://github.com/eugene-okulik/AoifeSidhe/assets/127910230/4461ffaa-ed74-4c66-972e-ed05d51bcdf8)

П.с. У пайчарма беда - он не обновдяет ошибку при исправлении. То есть я сделала опечатку - он подсветил. Я поправила - показывает по прежнему ошибку со старым значением.
Помогает - сtrl-x/ctrl-v =)

В картинках:

Ошибка:
![image](https://github.com/eugene-okulik/AoifeSidhe/assets/127910230/49ef0361-14b8-46c5-bf2f-af724ae9027d)

Все равно ошибка:
![image](https://github.com/eugene-okulik/AoifeSidhe/assets/127910230/bcb052bb-dc53-4392-bad2-5788782cb43a)

2023-12-16 07:29 UTC, eugene-okulik requested changes

2023-12-16 07:29 UTC, eugene-okulik commented on homework/aoife_sidhe/lesson_4/task.py
> +my_dict['prices_dict']['(\'i am a tuple\',)'] = 100  # add a new key-value pair
На что похоже `('i am a tuple', )`, на какой тип данных? И что говорит текст внутри нее?  
Сейчас тот ключ, который ты добавила, это строка `'(\'i am a tuple\',)'`. И, кстати, можно играться разными кавычками, чтобы не приходилось расставлять эти слеши: `"('i am a tuple',)"`

2023-12-16 15:51 UTC, AoifeSidhe commented on homework/aoife_sidhe/lesson_4/task.py
> +my_dict['prices_dict']['(\'i am a tuple\',)'] = 100  # add a new key-value pair
tuple похож на tuple
но если быть душным, то 
> добавьте элемент с ключом ('i am a tuple',) и любым значениемдобавьте элемент с ключом ('i am a tuple',) и любым значением

не отрицает что этот элемент может быть хоть чем угодно =)
Но по факту - надо было добавить tuple в словарь?)

Переделаю =)
Правда тапл потянул за собой еще пару изменений, но их тоже внесу.

2023-12-16 23:35 UTC, AoifeSidhe commented on homework/aoife_sidhe/lesson_4/task.py
> +my_dict['prices_dict']['(\'i am a tuple\',)'] = 100  # add a new key-value pair
![image](https://github.com/eugene-okulik/AoifeSidhe/assets/127910230/9aee851a-c79d-4fb5-8eaa-40aad79ff9a9)

and

![image](https://github.com/eugene-okulik/AoifeSidhe/assets/127910230/32436716-63b7-42d1-ac47-4726c0b83a79)

2023-12-16 23:42 UTC, AoifeSidhe commented on homework/aoife_sidhe/lesson_4/task.py
> +my_dict['prices_dict']['(\'i am a tuple\',)'] = 100  # add a new key-value pair
Сделала файл clear_task чтобы можно было посмотреть код без моих подробных комментариев для самой себя.
Все остальные файлы - это мне на будущее, чтобы в голове уложить информацию.

Код теперь даже показывает, что наш тапл - это тапл, а не какой-то там стринг или, ужас какой, float =)
Прикрутила простое меню иначе проверять этот ужас в терминале было невыносимо.
Меню, кстати, на словаре работает.

2023-12-17 17:36 UTC, eugene-okulik approved these changes
Ничего себе какая куча файлов!  
Файла с чистым выполнением домашнего задания я так и не нашел, даже в этом simple_task есть куча кода, который я не очень понимаю что делает.  
Если ты хочешь экспериментировать, то создай отдельную папку в папке с заданием, назови это папку "сюда не смотри" и складывай туда эксперименты, а то не понятно где мне нужно проверить домашнее задание. И в самом выполнении сложно среди экспериментов найти то, что было в задании.  
А с котрежем - я хотел обратить внимание на то, что кортеж может быть ключом словаря и заодно обратить внимание на то как оформляется кортеж с одним элементом.

2023-12-17 17:36 UTC, merged

2023-12-17 20:12 UTC, AoifeSidhe commented
>  этом simple_task есть куча кода, который я не очень понимаю что делает
Там одна кучка - это проверка на то tuple на то, что это именно он. Потому что я в этом моменте как раз хотела дополнительную проверку, что оно именно так, а я не ошиблась.
А вторая кучка - просто красиво печатает это все в терминал =)
Потому что простой принт выдает какую-то не очень читаемую строку. 

А часто ли tuple используется как ключ?

Создам тогда внутри паку - experiments и буду скаладывать свою доп работу туда.

2023-12-17 20:41 UTC, eugene-okulik commented
> > этом simple_task есть куча кода, который я не очень понимаю что делает
> > Там одна кучка - это проверка на то tuple на то, что это именно он. Потому что я в этом моменте как раз хотела дополнительную проверку, что оно именно так, а я не ошиблась.
> > А вторая кучка - просто красиво печатает это все в терминал =)
> > Потому что простой принт выдает какую-то не очень читаемую строку.
> 
> А часто ли tuple используется как ключ?
> 
> Создам тогда внутри паку - experiments и буду скаладывать свою доп работу туда.

Не, не часто. Но когда это нужно, то неочевидно, что такое можно делать. Поэтому я вот и обращаю внимание, чтобы в голове это осталось  
А то для меня это было чуть ли не открытием однажды, хотя я уже тогда и не новичком был.